In [1]:
import numpy as np    # numberical python

In [2]:
l = ["sudh",1,2,3,4]

In [3]:
l

['sudh', 1, 2, 3, 4]

In [4]:
type(l)

list

In [5]:
np.array(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U4')

In [6]:
type(np.array(l))    #ndarray means n dimensional array

numpy.ndarray

In [7]:
a1 = np.array([3,4,5,6,3.0])   # upcast ---- numpy type casts all interger to floating as one value is float in the list

In [8]:
a1

array([3., 4., 5., 6., 3.])

In [9]:
a = np.array([[1,2],[3,4]])

In [10]:
a

array([[1, 2],
       [3, 4]])

In [11]:
# pick 4 from above array

a[0]

array([1, 2])

In [12]:
a[1]

array([3, 4])

In [13]:
a[1][1]      # to extract 4 from above

4

In [14]:
a1

array([3., 4., 5., 6., 3.])

In [15]:
a1[1]

4.0

In [16]:
a2= np.array([1,2,3,4],ndmin=4)    # here four [[[[ bracket indicates 4D

In [17]:
a2

array([[[[1, 2, 3, 4]]]])

In [18]:
#to access value 1 from 4D

a2[0][0][0][0]

1

In [19]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [20]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [21]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [22]:
#matrix

In [23]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [24]:
a=[1,2,3,4,5]

In [25]:
np.asarray(a)

array([1, 2, 3, 4, 5])

In [26]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [27]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [28]:
 # matrix is subclass/child of an array tha is why asanyarray will not convert into an array 
 # bcoz it is alreay a matrix which is a alreay a form of array itself.

In [29]:
  np.asanyarray(np.mat(a))    



matrix([[1, 2, 3, 4, 5]])

In [30]:
#numpy.fromfunction() function construct an array by executing a function over each coordinate and the resulting array, 
#therefore, has a value fn(x, y, z) at coordinate (x, y, z).

In [31]:
np.fromfunction(lambda i , j : i==j, (3,3) )       

# i=row(0,1,2), j=column(0,1,2), (3,3) tuple as shape parameter to create 3X3 2D array

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [32]:
np.fromfunction(lambda i , j : i*j, (4,4) )       #BY DEFAULT numpy returns floating point numbers

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [33]:
np.fromfunction(lambda i , j : i*j, (4,4) , dtype = int)   # change defalt float into integer using dtype parameter

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [34]:
#3D array

np.fromfunction(lambda i , j , z : i*j*z, (3,3,2) , dtype = int)   

(3,3,2) means we are looking for 3 such matrix of dimension 3x2 
(z,x,y) axis, z is depth of the array.

SyntaxError: invalid syntax (<ipython-input-34-e57463a509b7>, line 5)

In [ ]:
#4D array

np.fromfunction(lambda i , j , z , p : i*j*z*p , (4,3,2,2) , dtype = int) 

# (4,3,2,2) means we have 2x2 -- 3 such arrays with 4 combinations -- reading from backwards

In [ ]:
a = np.fromfunction(lambda i , j , z : i*j*z , (4,3,2) , dtype = int) 

In [ ]:
a


In [ ]:
#check dimension of array / no of axis 

a.ndim

In [ ]:
# total no of elements in the entire array i.e. 4*3*2 = 24

a.size

In [ ]:
#dimensions value

a.shape

In [ ]:
a.dtype

In [ ]:
#if you try to convert a 3D or above array to dataframe using pandas then it gives ValueError: Must pass 2-d input
#pandas can convert 2D to dataFrame
#for converting 3D array to DF, we need to reshape or flatten the 3D array

a = np.fromfunction(lambda i ,j: i*j , (4,3) , dtype = int) 

In [ ]:
import pandas as pd

pd.DataFrame(a)

In [ ]:
a = np.fromfunction(lambda i , j , z : i*j*z , (4,3,2) , dtype = int)   

In [ ]:
b = a.reshape(2,12) 

# 2D --> (12,2) or (8,3) or (12,1) etc
# 4d --> (2,4,3,1) or (3,4,1,2)  etc
# convert to 2D or other any other dimension using reshape func, just the multiple of all shapes should be equal to the size of array/ no. of elements in the array
b

In [ ]:
# converting to pandas DF

pd.DataFrame(b)

In [ ]:
a.reshape(2,-123)    # or (4,-1) etc any -ve number will automatically take the remaining shape value to match the size of array

In [ ]:
#The numpy.random.rand() function creates an array of specified shape and fills it with random values.
#to generate random value in the given shape


np.random.rand(10,4)   #10x4 -- shape/dimension

In [ ]:
#to generate random integer between given range
#Return random integers from `low` (inclusive) to `high` (exclusive).

np.random.randint(4,100)

In [ ]:
# The numpy.random.randn() function creates an array of specified shape and fills it with random values as per standard normal distribution.
# If positive int_like arguments are provided, `randn` generates an array of shape ``(d0, d1, ..., dn)``, filled with random floats sampled from a univariate "normal" (Gaussian) distribution of mean 0 and variance 1. A single float randomly sampled
# from the distribution is returned if no argument is provided.

np.random.randn(4,5)

In [ ]:
list(range(2,10,2))

In [ ]:
#numpy equivalent of range ...just this numpy function can take floating point number as input.

a1=np.arange(2,10.5,.5)

In [ ]:
a1[0:5]       # slicing will work same as list

In [ ]:
arr = np.random.rand(4,5)

In [ ]:
arr

In [ ]:
# extract all data from arr which is greater than .5

In [ ]:
arr > .5

In [ ]:
arr[arr > .5]

In [ ]:
arr

In [ ]:
#fetch required data from array 
# you can use pandas .loc and iloc function also but first convert array into dataframe.

arr[[1,2],[2]]

In [ ]:
arr = np.random.rand(8,5)

In [ ]:
arr

In [ ]:
arr[1:8 , 0:3]      

In [ ]:
a2 = arr[1:8 , [0,1,2]]             #same as above 

In [ ]:
a2

In [ ]:
a2[0][0]

In [ ]:
#change a2[0][0]  value to something else

a2[0][0] = 1000

In [ ]:
a2

In [ ]:
a = np.array([[1,2] ,[3,4]])
b = np.array([[2,3] , [4,5]])

In [ ]:
a

In [ ]:
b

In [ ]:
a*b     #element wise multiplication

In [ ]:
m=a@b       # matrix multiplication 



In [ ]:
m

In [ ]:
m/0

In [ ]:
######

In [ ]:
np.zeros(5)    # 1D array with zeroes

In [ ]:
np.zeros((3,5))    #2d array

In [ ]:
np.zeros((3,5,4))  #3d array  --- 3 arrays of dimesion 5x4

In [ ]:
np.ones(6)

In [ ]:
5 + np.zeros((2,3))       # broadcasting

In [ ]:
np.empty((3,4))  

#Return a new array of given shape and type, with random values. empty, 
#unlike zeros, does not set the array values to zero, and may therefore be marginally faster.

In [ ]:
np.linspace(2,6)

#The numpy.linspace() function returns number spaces evenly w.r.t interval. 
#Similar to numpy.arange() function but instead of step it uses sample number.

In [ ]:
np.linspace(2,6,5)     # (start,stop,No. of samples to generate)

In [ ]:
np.linspace(2,6,10).reshape(5,2)  # convert to 2D

In [ ]:
   np.linspace(2,6,10,endpoint = False)       # endpoint = false removes last element 

In [ ]:
   np.linspace(2,6,10,endpoint = False,retstep=True)   # returns the stepsize which the system is using

In [ ]:
 np.logspace(2,6,10,base=10)    
    
# It creates an array by using the numbers that are evenly separated on a log scale.

In [ ]:
a=np.arange(4,40).reshape(3,6,2)

In [ ]:
a

In [ ]:
a.max()

In [ ]:
a.max(axis=1)          # column wise maximun from each arrays

In [ ]:
a=np.arange(4,40).reshape(6,6)

In [ ]:
a

In [ ]:
a.max(axis=0)      #row wise  -- 4,10,16,22,28,34

In [ ]:
a.max(axis=1)      # column wise -- 4,5,6,7,8,9

In [ ]:
10 + a

In [ ]:
a **2

In [ ]:
pow(a,3)           #power

In [ ]:
a

In [ ]:
b = np.array([2,3,1,2,3,4])

In [ ]:
a+b      # broadcasting ----- here row wise addition  note: keep same no. of element in array b

In [ ]:
# firtst convert to 2d 

b = b.reshape(1,-1).T

#FOR COLUMN WISE OPERATION , we need to rotate the array i.e. transpose it 

b

In [ ]:
a+b

In [ ]:
np.sqrt(a)

In [ ]:
np.exp(a)

In [ ]:
np.log10(a)

In [ ]:
# deep & shallow copy

x=np.array([1,2,3])

In [ ]:
x

In [ ]:
y = x              #shallow copy... any modification made to X OR Y will be reflected in both as they refer to same memory

In [ ]:
y

In [ ]:
z = np.copy(x)          #deep copy ....copy data to new loaction any modification made to x will not reflect in Z.

In [ ]:
z

In [ ]:
x[0]=100                

In [ ]:
y

In [ ]:
id(z)

In [ ]:
id(x)

In [ ]:
id(y)

In [ ]:
id(x[0])

In [ ]:
id(y[0])

In [ ]:
id(x[0]) == id(y[0])       #????

In [ ]:
id(x[0]) == id(y[2])     # ????

In [ ]:
c='sudh'

In [ ]:
id(c) == id(x[0])